# coding: utf-8

"""
    PirlPay API

    The PirlPay API for automated payment processing  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@pirl.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pirlpay
from pirlpay.catalogs_api import CatalogsApi  # noqa: E501
from pirlpay.rest import ApiException


class TestCatalogsApi(unittest.TestCase):
    """CatalogsApi unit test stubs"""

    def setUp(self):
        self.api = pirlpay.catalogs_api.CatalogsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_catalogs_products_create(self):
        """Test case for catalogs_products_create

        """
        pass

    def test_catalogs_products_list(self):
        """Test case for catalogs_products_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
