# coding: utf-8

"""
    PirlPay API

    The PirlPay API for automated payment processing  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@pirl.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pirlpay
from pirlpay.billing_api import BillingApi  # noqa: E501
from pirlpay.rest import ApiException


class TestBillingApi(unittest.TestCase):
    """BillingApi unit test stubs"""

    def setUp(self):
        self.api = pirlpay.billing_api.BillingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_billing_products_transactions_create(self):
        """Test case for billing_products_transactions_create

        """
        pass

    def test_billing_products_transactions_list(self):
        """Test case for billing_products_transactions_list

        """
        pass

    def test_billing_simple_payment_transactions_create(self):
        """Test case for billing_simple_payment_transactions_create

        """
        pass

    def test_billing_simple_payment_transactions_list(self):
        """Test case for billing_simple_payment_transactions_list

        """
        pass

    def test_billing_subscriptions_create(self):
        """Test case for billing_subscriptions_create

        """
        pass

    def test_billing_subscriptions_list(self):
        """Test case for billing_subscriptions_list

        """
        pass

    def test_billing_subscriptions_transactions_list(self):
        """Test case for billing_subscriptions_transactions_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
