# coding: utf-8

"""
    PirlPay API

    The PirlPay API for automated payment processing  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@pirl.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pirlpay
from pirlpay.payments_api import PaymentsApi  # noqa: E501
from pirlpay.rest import ApiException


class TestPaymentsApi(unittest.TestCase):
    """PaymentsApi unit test stubs"""

    def setUp(self):
        self.api = pirlpay.payments_api.PaymentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_payments_billing_plans_create(self):
        """Test case for payments_billing_plans_create

        """
        pass

    def test_payments_billing_plans_list(self):
        """Test case for payments_billing_plans_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
